/******************************************************************************/
/***       Generated by IBExpert 2009.08.17 02/11/2009 07:02:25 p.m.        ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES ISO8859_1;

CREATE DATABASE 'D:\RAD Studio\Projects\tpv\srv\bin\BD.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET ISO8859_1;

